### ISSUE TITLE
Are there any explanations and resources of the datasets

### ISSUE THREAD

**Issue by LazyLaker** [ErikinBC/SurvSet#1]

**Comment by eugenebaraka** [comment]
I really second this. Datasets need data dictionaries to easily understand what they are about and which variables we have. I can also help with this! Please let me know if you need help @ErikinBC

**Comment by ErikinBC** [comment]
Hi folks,

Currently the way to look up the dataset would to refer to the associated [arxiv paper](https://arxiv.org/pdf/2203.03094.pdf). It would be a bit of work to create data dictionaries for each of them, but I'll keep it in mind for this year.

<img width="563" alt="image" src="https://user-images.githubusercontent.com/7805021/229347772-e876329a-f2d1-4d68-a1b7-96048e41bfec.png">
