### ISSUE TITLE
Datasets with competing risks?

### ISSUE THREAD

**Issue by peterchristofferholm** [ErikinBC/SurvSet#2]
Great idea creating this package - I was scouring the internet looking for public survival datasets, so stumbling on this was very welcome.

I am going throught the different datasets, but it would be helpful to have some additional overview with the details on each of them. I, for one, would be interested in quickly being able to see if any of your included datasets can be used as an example of competing risks.

Thanks
Peter

**Comment by ErikinBC** [comment]
Hi @peterchristofferholm , as mentioned in this [reply](https://github.com/ErikinBC/SurvSet/issues/1#issuecomment-1493293790), right now you'll need to refer to associated arxiv paper.
