### ISSUE TITLE
Package for R

### ISSUE THREAD

**Issue by lena-222** [ErikinBC/SurvSet#3]
Great idea creating this package!

Have you thought about implementing an R version of this package? I think it would be useful for a lot of people (of course for me too).

Thanks
Lena

**Comment by ErikinBC** [comment]
Hi Lena, thanks for reaching out. All of the raw data can be found in the following folder for R users (although not very satisfactory I admit):

https://github.com/ErikinBC/SurvSet/tree/main/SurvSet/_datagen/output

If you'd like to create an R-package version with this data, please feel free to ahead and do so. Happy to thought partner on it if you want to shoot me an email at erikinwest@gmail.com.
